name = "cf-worker-ws-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[vars]
# UUID = "bc3d7a46-3ff0-412d-9407-51944e8fc6c7"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "271a1baa-11c7-4426-a3a5-ceaebce4e70c,fa93c0a3-75c2-4f71-87f1-45e2c139e78c,8f206c34-f5ef-4b54-811a-cd232aa8fd29"
